import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Headers/Header06/Header";
import Footer from "../components/Footers/Footer01/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "miaq. Web Components",
  description: "Generated by miaq. Web Components",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
